server:
  port: 8761

eureka:
  instance:
    # 单机 hostname: localhost #eureka注册中心实例名称
    hostname: EurekaServer1
  client:
    #是否将自己这个服务注册到EurekaServer中；单机环境中设置为false，集群环境默认。
    registerWithEureka: true
    #表示是否从Eureka Server获取注册信息；单机环境中设置为false，集群环境默认。
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://EurekaServer1:8761/eureka/,http://EurekaServer2:8762/eureka/,http://EurekaServer3:8763/eureka/,http://EurekaServer4:8764/eureka/,http://EurekaServer5:8765/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: true