server:
  port: 8081

spring:
  application:
    name: demo-client1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
    #提高client 端 拉取Server 注册信息的频率(默认 30)
    registry-fetch-interval-seconds: 5