server:
  port: 8762

eureka:
  instance:
    hostname: EurekaServer2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://EurekaServer1:8761/eureka/,http://EurekaServer2:8762/eureka/,http://EurekaServer3:8763/eureka/,http://EurekaServer4:8764/eureka/,http://EurekaServer5:8765/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: true