server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #是否将自己这个服务注册到EurekaServer中；单机环境中设置为false，集群环境默认。
#    registerWithEureka: false
    #表示是否从Eureka Server获取注册信息；单机环境中设置为false，集群环境默认。
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8762/eureka/,http://${eureka.instance.hostname}:8763/eureka/
  server:
      waitTimeInMsWhenSyncEmpty: 0