server:
  port: 8765

eureka:
  instance:
    hostname: EurekaServer5
    #client发送心跳的频率(默认 30)
    lease-renewal-interval-in-seconds: 10
  client:
    #是否将自己这个服务注册到EurekaServer中；单机环境中设置为false，集群环境默认。
    registerWithEureka: true
    #表示是否从Eureka Server获取注册信息；单机环境中设置为false，集群环境默认。
    fetchRegistry: true
    #提高client 端 拉取Server 注册信息的频率(默认 30)
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://EurekaServer1:8761/eureka/,http://EurekaServer2:8762/eureka/,http://EurekaServer3:8763/eureka/,http://EurekaServer4:8764/eureka/,http://EurekaServer5:8765/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: true
    #触发自我保护的心跳数比例阈值(默认 0.85)
    renewal-percent-threshold: 0.5